### ISSUE TITLE
Please add local in remotes

### ISSUE THREAD

**Issue by revengel** [kaczmarkiewiczp/rcloneExplorer#149]
Please add local in remotes

**Comment by kaczmarkiewiczp** [comment]
Local remote support is added in #162 and will be available in the next release (v1.5.0).

However, I would advise against using this method as a regular, every day file explorer. It's not as optimized as any other other app that's sole purpose is being a file explorer. All the commands are going through rclone which adds extra overhead. Also since the app was designed in mind with cloud remotes, some of the UI elements are not very intuitive for local remotes (i.e. download or upload buttons). Currently I have no plans to optimize anything specifically for local remotes.

Having said that, all the features of the app should work properly with local remotes. I'm imagining that the best usage of the local remote is together with the crypt remote. That way files on the device can be encrypted or decrypted using rclone.
