### ISSUE TITLE
Save to SD card and not only to system memory

### ISSUE THREAD

**Issue by drejjmit** [kaczmarkiewiczp/rcloneExplorer#155]
The ability to save to mount points.

**Comment by kimperator** [comment]
And to upload from SD Card

**Comment by kaczmarkiewiczp** [comment]
I added an option to upload from SD card in #170. 

Initially I thought that saving to SD card would also be possible, but after working on this I seemed to have hit a wall. In order to write to SD cards, Rclone Explorer needs to request separate write permission for SD card. After user grants the permission, Rclone Explorer can only write to the SD card using storage access framework. However it's the rclone binary that handles the downloading and saving of files. Since the rclone binary doesn't use Android's storage access framework, any attempt to write to the SD card ends in permission denied errors. Unfortunately I do not see a way around this.

There is a workaround that will allow saving to SD card, however. You could 'HTTP serve' a file or a folder, and then download it from your browser. Most browsers should allow to save to SD card.

**Comment by kimperator** [comment]
Hello, is it possible to don't limit the folder restriction to /sdcard ?

I mean with magisk and root, it's possible to rw mount the sd card to /mnt/media_rw

so if I could reach the folder from within the app, it should be enough.

Thanks,
kImperator

**Comment by kaczmarkiewiczp** [comment]
I've been thinking about this issue for the last couple of days. I tried some things and it seems that the SD card shows as writable but it's the Android OS denying write access unless the app goes through the official API to ask for permission.

I'm aware that there are apps that can "unlock" the SD card to all apps using root, but I would not want to show access to the SD card in my app if it means that it's going to fail for most of the users.

However I discovered that apps are allowed to write to their own directory on the SD card without requiring any extra permissions. So when saving files, it would be possible to save to the SD card under `/sdcard/Android/media/`. From there you can move files to any other directory on the SD card using any file manager. This implementation would allow everyone to save directly to the SD card, whether they have root or not.
