### ISSUE TITLE
Asking for password when rclone.conf is not encrypted

### ISSUE THREAD

**Issue by geerew** [kaczmarkiewiczp/rcloneExplorer#200]
When I import an unencrypted rclone.conf, I am asked for a password.

Below is my rclone.conf file

```
[drive]
type = drive
client_id = 
client_secret = 
token = {xxx}

[crypt]
type = crypt
remote = drive:/crypt
filename_encryption = standard
password = xxx
password2 = xxx
```

**Comment by kaczmarkiewiczp** [comment]
Since rclone doesn't provide an official way of checking if config file is encrypted or not, rcloneExplorer runs `rclone --ask-password=false listremotes` and checks the exit value. If there was an error, rcloneExplorer assumes that this means that the config file is encrypted.

In my testing this was the best workaround, since simple command like `listremotes` should not fail. So why did it fail? There are two cases I can think of in which `listremotes` would return an error:

1. The imported config file is not recognized by rclone. Are you importing the correct file?
2. The rclone binary architecture does not match the device you're running. This means that for example you downloaded ARM64 or x86 version when your device is ARM32. Which rcloneExplorer version did you download, and what device are you running it on?

**Comment by geerew** [comment]
Hi. Thanks for the quick reply.

You are 100% correct with suggestion 2. I must have install the x86 instead of the ARM64. 

It's working now. 

Thanks again
