### ISSUE TITLE
Can't download to external storage

### ISSUE THREAD

**Issue by FoxP** [kaczmarkiewiczp/rcloneExplorer#201]
Hello,

rcloneExplorer seems to not be able to download to external storage (microSD card).
  
I have a 32 Go internal storage (named "sdcard" on rcloneExplorer, but it's not a microSD card) and my real external 64 Go microSD card is not detected.
  
![screenshot_20180813-195153](https://user-images.githubusercontent.com/16615901/44048741-8ed40702-9f32-11e8-8a48-dedcad6dafd9.png)
    
Plus, two entries are flagged as "storages" but they are not. See screenshot below:
  

![screenshot_20180813-195110](https://user-images.githubusercontent.com/16615901/44048765-9dc6298e-9f32-11e8-81cd-77c3cb62f2f1.png)
    
- **Phone:** Xiaomi Redmi Note 3 Pro Prime (ARM64)
- **System:** LineageOS 13 Official Stable build (Android 6.0.1_r81 with security patch level 2018-06-05).

**Comment by kaczmarkiewiczp** [comment]
Starting with Android KitKat, apps are required to use Storage Access Framework in order to freely write to external storage. On rcloneExplorer, rclone is in charge of saving files, so there's no way of using official Android API to save files. I had to use a hacky way to support saving to external storage. Apps can still save to external storage without using Storage Access Framework, but only to the app's folder. So this is exactly what rcloneExplorer does. It saves files to app's media folder on the external storage. This means that if you want to save your files to a specific folder on your external SD card, you'll have to use a file explorer to move them afterwards.

So looking at your last screenshot:

1. `/sdcard` is your internal storage
2. `/storage/emulated/0/Android/media/ca.pkay.rcexplorer` is also the internal storage. This entry should not be displayed here, and is a side effect of adding support for external storage. I'm trying to figure out a way not to display it here.
3. `/storage/86E0-9033/Android/media/ca.pkay.rcexplorer` this should be your external SD card

Have you tried selecting the third storage? Does it not work?

**Comment by FoxP** [comment]
Selecting the third storage may work but it won't allow to sync / backup the `DCIM` folder (for instance) with a rclone-compatible remote. I'm ok to download to `/storage/86E0-9033/Android/media/ca.pkay.rcexplorer` and move everything afterwards, but not being able to sync my external SD card pictures / videos / files is a huge limitation. :smiley:

**Comment by kaczmarkiewiczp** [comment]
I really can't figure out a way around this. Since rclone doesn't use Storage Access Framework, it can only save to the media folder on any external SD card. :disappointed: 

I looked at termux, if it handles external SD cards differently, but it also saves to the apps' data folder on external card.

**Comment by FoxP** [comment]
Ok, thanks for your answer. I have opened an issue: https://github.com/ncw/rclone/issues/2468

**Comment by kaczmarkiewiczp** [comment]
I do not believe this issue is something that can be fixed in rclone either. 

[Here's a link](https://stackoverflow.com/questions/26744842/how-to-use-the-new-sd-card-access-api-presented-for-android-5-0-lollipop) that goes in detail what's required in order to have full write access to external SD card. 

Basically it requires to launch an intent asking user for write access, checking the result, and then using the supplied Uri (Android doesn't return paths in a format that rclone uses) to write to external SD card using Storage Access Framework.

This means that rclone would need to use Android APIs, which in turn would require it to be written in Java (or Kotlin) and compiled for Android. Therefore I don't think it's something that can be easily addressed :disappointed:

**Comment by FoxP** [comment]
So basically, if rcloneExplorer (written in Java) has external SD access, it means that rclone (written in Go) won't inherit? :disappointed: Ok, i understand now.
