### ISSUE TITLE
Request - add mount

### ISSUE THREAD

**Issue by joemarshalljm** [kaczmarkiewiczp/rcloneExplorer#225]
Is there any way to mount the drive so other apps can access?

**Comment by patrykcoding** [comment]
Mounting is not possible due to limitations in Android, but you could "serve" a remote, thus making it accessible to other apps.

Open the remote you want to serve. Press the options button at the top right corner (optionally, you can press the options button next to a file/folder to serve only that file/folder), and select "Serve". You have an option of three protocols (HTTP, FTP, and Webdav). If you want other apps to have read and write access, then you want to go with either FTP or Webdav. Finally, a notification will appear showing you the address and port on which the remote is being served.
