### ISSUE TITLE
not streaming video file from mega?

### ISSUE THREAD

**Issue by caspertone2003** [kaczmarkiewiczp/rcloneExplorer#232]
@kaczmarkiewiczp 
I have installed last version. I streamed in the past videos from mega, I believe with this version.
Was not using it for a time. Tried several days lately and it gets stuck in wainting but no streaming starts.
Any hint?
Changes in mega?
Thanks
CT

**Comment by x0b** [comment]
Do you still experience this problem? I could not reproduce, it works as intended (on 2019-07-16).

**Comment by caspertone2003** [comment]
Yes, I still experience this problem. Should you wish me to do any test... I am ready.
CT

**Comment by x0b** [comment]
Just for clarification: Are you opening the file by tapping the entry in the list? Or via ```⋮``` > ```Open As``` > ```Video```?

Tapping an entry always downloads it first before trying to open it - which can take a while depending on your internet connection, network congestion and the cloud provider (mega).

I guess rcloneExplorer could try to be smarter by implementing a file size and/or extension mapping mechanism for (large) video files.

Can you try to play it via  ```⋮``` > ```Open As``` > ```Video```?

**Comment by caspertone2003** [comment]
@x0b 
ahhhh
I have been using it with open as etc. that works nicely. I believed that that was not streaming....
I was expecting it to stream directly tapping on the entry... 
Perhaps a note somewhere explaining the situation would help others... or a swith in the behaviours... could you not programm tapping making as current open as? it would be more intuitive... And then, ithe other options could be "download and open as"....

Probably the change does not merit the effort ... if not within an update for another reason 

So, streaming works nicely, but I was misunderstanding it.

Big thanks!

**Comment by x0b** [comment]
No problem.

However, your response prompted me to look a bit closer. It turns out, that ```.mkv``` files on mega remotes are returned as ```application/octet-stream``` (possibly as a result of [rclone failing to correctly guess the file type](https://github.com/rclone/rclone/blob/f78cd1e0434ee597fb8937ba3cda0d5fd58becfe/fs/mimetype.go#L11)). 

When everything works as it should, rclone already recognizes both audio and video files and streams them directly. However, this did not work automatically on mega remotes with some file types. Unrecognized mimeTypes will now also be queried against the Android Database.

This change should land in the next version. Until then, Open As > Video should work just as well.

**Comment by caspertone2003** [comment]
Thanks again!
