### ISSUE TITLE
My rclone.conf has two passwords for my crypt drive and I cannot unlock it 

### ISSUE THREAD

**Issue by hanglearning** [kaczmarkiewiczp/rcloneExplorer#259]
While importing my rclone.conf, the app shows that "Configuration is password protected". When I press to unlock, no matter which password I give, it never passes. Which password shall I use to unlock my config file? Thanks.

**Comment by x0b** [comment]
In general, when rclone can't read the configuration file it assumes that it must be password protected and will prompt you for a password. There are multiple reasons as to why this might not work:
1. The file is not encrypted, but causes a different error
2. Your configuration file is encrypted, but the password contains a special character that somehow does not work
3. You entered a wrong password.

Do you have a password set on the configuration file? Because if not, then it's basically just option 1.

**Comment by hanglearning** [comment]
@x0b thanks for your prompt reply! I don't think I have a password set on the config file. I just directly copied my config file from my Mac to my phone via Android file transfer. My config file just has a normal gdrive and a crypt drive on top of the normal gdrive which has two passwords. 

I guess then it's due to option 1..

**Comment by x0b** [comment]
What happens when you try it out with the [latest release from my fork](https://github.com/x0b/rcloneExplorer/releases)?

**Comment by hanglearning** [comment]
@x0b wow hey you know what! Your build works a charm! Once I imported the config file two drives just showed up in the list! I didn't know you have a fork. Thanks for your help I really appreciate it! :grin:

**Comment by hanglearning** [comment]
Solved
